version: "3.8"

services:

  php:
    build:
      context: .
      args:
        - arch=
        - version=7.3.22
        - build=dev
    image: leadstec.tencentcloudcr.com/leadstec/php:7.3.22
    ports:
      - "50301:80"
    volumes:
      - ~/volumes/php.local/log:/data/log
      - ~/volumes/php.local/persist:/data/persist
      - ~/volumes/cache/php:/data/cache
    env_file:
      - ./env
    environment:
      - EMAIL=
      - LCS_LOG_LEVEL=debug
    secrets:
      - lcs
    hostname: php.local
    container_name: php.local

secrets:
  lcs:
    file: ~/.vcubi/lcs
